Improved wrapper scripts.

diff --git a/.local/bin/termux/xwallpaper b/.local/bin/termux/xwallpaper
--- a/.local/bin/termux/xwallpaper
+++ b/.local/bin/termux/xwallpaper
@@ -2,15 +2,15 @@
 
 # xwallpaper wrapper for Termux
 
-if [ -n "$TMUX" ]; then
-	for o in "$@"; do case "$o" in
+if [ -n "${TMUX}" ]; then
+	for o in "${@}"; do case "${o}" in
 		--o*|--sc*|--tr*) shift 2 ;;
 		--*) shift ;;
 	esac done
-	[ -f "$1" ] || { echo "File not found: $1" ; exit 1 ;}
-	file="$(readlink -f "$1")"
-	termux-wallpaper -f "$file" >/dev/null 2>&1
-	termux-wallpaper -l -f "$file" >/dev/null 2>&1
+	[ -f "${1}" ] || { echo "File not found: ${1}"; exit 1 ;}
+	f="$(readlink -f "${1}")"
+	termux-wallpaper -f "${f}" >/dev/null 2>&1
+	termux-wallpaper -l -f "${f}" >/dev/null 2>&1
 else
-	"$PREFIX/bin/xwallpaper" "$@"
+	"${PREFIX}/bin/xwallpaper" "${@}"
 fi
